# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Excalidraw installation tasks
  when: excalidraw_room_enabled | bool
  tags:
    - setup-all
    - setup-excalidraw
    - install-all
    - install-excalidraw
  block:
    - name: Validate Excalidraw configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Prepare HTTP Basic authentication for Excalidraw
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/prepare_basic_auth.yml"
    - name: Install Excalidraw
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Excalidraw uninstallation tasks
  when: not excalidraw_room_enabled | bool
  tags:
    - setup-all
    - setup-excalidraw
  block:
    - name: Uninstall Excalidraw
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
