# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Excalidraw collaboration server installation tasks
  when: excalidraw_room_enabled | bool
  tags:
    - setup-all
    - setup-excalidraw-room
    - install-all
    - install-excalidraw-room
  block:
    - name: Validate Excalidraw collaboration server configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Excalidraw collaboration server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Excalidraw collaboration server uninstallation tasks
  when: not excalidraw_room_enabled | bool
  tags:
    - setup-all
    - setup-excalidraw-room
  block:
    - name: Uninstall Excalidraw collaboration server
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
