# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Excalidraw collaboration server settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - excalidraw_room_uid
    - excalidraw_room_gid
    - excalidraw_room_hostname
    - excalidraw_room_path_prefix
    - excalidraw_room_container_network

- name: Run if Traefik is enabled
  when: excalidraw_room_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Excalidraw collaboration server Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - excalidraw_room_container_labels_traefik_hostname
        - excalidraw_room_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `excalidraw_room_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if excalidraw_room_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          excalidraw_room_container_labels_traefik_path_prefix (`{{ excalidraw_room_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/excalidraw`).
      when: "excalidraw_room_container_labels_traefik_path_prefix != '/' and excalidraw_room_container_labels_traefik_path_prefix[-1] == '/'"
