# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "lookup('ansible.builtin.varnames', ('^' + item.old + '$'), wantlist=True) | length > 0"
  with_items:
    - { "old": "excalidraw_room_http_header_content_permission_policy", "new": "excalidraw_room_http_header_permissions_policy" }

- name: Fail if required Excalidraw collaboration server settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - excalidraw_room_uid
    - excalidraw_room_gid
    - excalidraw_room_hostname
    - excalidraw_room_path_prefix
    - excalidraw_room_container_network

- name: Run if Traefik is enabled
  when: excalidraw_room_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Excalidraw collaboration server are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - excalidraw_room_container_labels_traefik_hostname
        - excalidraw_room_container_labels_traefik_path_prefix

    - name: Fail if excalidraw_room_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          excalidraw_room_container_labels_traefik_path_prefix (`{{ excalidraw_room_container_labels_traefik_path_prefix }}`) must be `/`.
          Excalidraw collaboration server does not support hosting under a subpath yet.
      when: "excalidraw_room_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `excalidraw_room_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if excalidraw_room_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          excalidraw_room_container_labels_traefik_path_prefix (`{{ excalidraw_room_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/excalidraw-room`).
      when: "excalidraw_room_container_labels_traefik_path_prefix != '/' and excalidraw_room_container_labels_traefik_path_prefix[-1] == '/'"
